services:
  cloudfilestorage:
    build: .
    ports:
      - '8081:8081'
    depends_on:
      - postgres
      - redis
      - minio
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/filestorage
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    volumes:
      - cloudfilestoragevolume:/app/data
    restart: unless-stopped
  postgres:
    image: 'postgres:17'
    environment:
      POSTGRES_DB: filestorage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5438:5432'
    volumes:
      - postgresvolume:/var/lib/postgresql/data
    restart: always
  redis:
    image: 'redis:7.2-alpine'
    ports:
      - '6379:6379'
    restart: always
    volumes:
      - redisvolume:/data

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # MinIO API
      - "9001:9001"   # MinIO Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
volumes:
  cloudfilestoragevolume:
    name: cloudfilestoragevolume
  postgresvolume:
    name: postgresvolume
  redisvolume:
    name: redisvolume
  minio_data:
    name: minio_data